"""Context management package (ch08): two-layer compaction + recovery."""

from __future__ import annotations

from mewcode.context.manager import (
    AGGREGATE_CHAR_LIMIT,
    AUTO_COMPACT_SAFETY_MARGIN,
    MANUAL_COMPACT_SAFETY_MARGIN,
    PERSISTED_TAG,
    SINGLE_RESULT_CHAR_LIMIT,
    SUMMARY_OUTPUT_RESERVE,
    SUMMARY_PROMPT,
    CompactCircuitBreaker,
    CompactEvent,
    ContentReplacementRecord,
    ContentReplacementState,
    FileReadRecord,
    RecoveryState,
    SkillInvocationRecord,
    append_replacement_records,
    apply_tool_result_budget,
    auto_compact,
    build_compact_messages,
    build_recovery_attachment,
    cleanup_tool_results,
    clone_replacement_state,
    compute_compact_threshold,
    create_replacement_state,
    ensure_session_dir,
    estimate_conversation_tokens,
    estimate_tokens,
    extract_summary,
    load_replacement_records,
    make_persisted_preview,
    persist_tool_result,
    reconstruct_replacement_state,
    should_auto_compact,
)

__all__ = [
    "SINGLE_RESULT_CHAR_LIMIT",
    "AGGREGATE_CHAR_LIMIT",
    "AUTO_COMPACT_SAFETY_MARGIN",
    "MANUAL_COMPACT_SAFETY_MARGIN",
    "SUMMARY_OUTPUT_RESERVE",
    "PERSISTED_TAG",
    "SUMMARY_PROMPT",
    "CompactEvent",
    "CompactCircuitBreaker",
    "ContentReplacementState",
    "ContentReplacementRecord",
    "FileReadRecord",
    "SkillInvocationRecord",
    "RecoveryState",
    "create_replacement_state",
    "clone_replacement_state",
    "reconstruct_replacement_state",
    "append_replacement_records",
    "load_replacement_records",
    "apply_tool_result_budget",
    "auto_compact",
    "compute_compact_threshold",
    "should_auto_compact",
    "estimate_tokens",
    "estimate_conversation_tokens",
    "extract_summary",
    "build_compact_messages",
    "build_recovery_attachment",
    "make_persisted_preview",
    "persist_tool_result",
    "ensure_session_dir",
    "cleanup_tool_results",
]
